name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install package
      run: |
        sudo apt-get -y install javacc
        
    - name: Compile Lox grammar 
      working-directory: Java-CC/sbt-project/Lox/loxparser
      run: sbt javacc
      
    - name: Run test 
      working-directory: Java-CC/sbt-project/Lox/loxparser
      run: sbt test
    
